"""
Generate complete index.html with ALL FileForge tools
"""

# Tool data - all actual tools that exist
tools_data = {
    "generators": [
        ("barcode.html", "📊", "Barcode Generator", "Generate barcodes and QR codes"),
        ("color-palette.html", "🎨", "Color Palette", "Generate color palettes"),
        ("credit-card.html", "💳", "Credit Card Generator", "Generate test credit card numbers"),
        ("css-border-radius.html", "📐", "CSS Border Radius", "Generate CSS border radius"),
        ("css-box-shadow.html", "💎", "CSS Box Shadow", "Generate CSS box shadows"),
        ("css-button.html", "🔘", "CSS Button", "Generate CSS button styles"),
        ("css-gradient.html", "🌈", "CSS Gradient", "Generate CSS gradients"),
        ("fake-address.html", "🏠", "Fake Address", "Generate fake addresses"),
        ("fake-email.html", "📧", "Fake Email", "Generate fake email addresses"),
        ("fake-name.html", "👤", "Fake Name", "Generate fake names"),
        ("favicon.html", "🎨", "Favicon Generator", "Create favicons from images"),
        ("gradient.html", "🌈", "Gradient Generator", "Generate gradients"),
        ("hash.html", "🔐", "Hash Generator", "Generate MD5, SHA-1, SHA-256 hashes"),
        ("html-boilerplate.html", "📄", "HTML Boilerplate", "Generate HTML boilerplate"),
        ("json-dummy-data.html", "📋", "JSON Dummy Data", "Generate JSON dummy data"),
        ("lorem.html", "📝", "Lorem Ipsum", "Generate placeholder text"),
        ("meta-tags.html", "🏷️", "Meta Tags", "Generate SEO meta tags"),
        ("open-graph.html", "🔖", "Open Graph", "Generate Open Graph tags"),
        ("otp.html", "🔑", "OTP Generator", "Generate one-time passwords"),
        ("password.html", "🔑", "Password Generator", "Generate secure passwords"),
        ("phone-number.html", "📱", "Phone Number", "Generate phone numbers"),
        ("qr-code.html", "📱", "QR Code", "Generate QR codes"),
        ("robots-txt.html", "🤖", "Robots.txt", "Generate robots.txt file"),
        ("sitemap.html", "🗺️", "Sitemap", "Generate XML sitemap"),
        ("tailwind-class.html", "💨", "Tailwind Class", "Generate Tailwind CSS classes"),
        ("twitter-card.html", "🐦", "Twitter Card", "Generate Twitter card meta tags"),
        ("username.html", "👤", "Username Generator", "Generate usernames"),
        ("uuid.html", "🆔", "UUID Generator", "Generate UUIDs"),
    ],
    "calculators": [
        ("age.html", "🎂", "Age Calculator", "Calculate age from date of birth"),
        ("bmi.html", "⚖️", "BMI Calculator", "Calculate Body Mass Index"),
        ("bmr.html", "🔥", "BMR Calculator", "Calculate Basal Metabolic Rate"),
        ("calorie.html", "🍎", "Calorie Calculator", "Calculate daily calorie needs"),
        ("compound-interest.html", "💰", "Compound Interest", "Calculate compound interest"),
        ("currency.html", "💱", "Currency Converter", "Convert currencies"),
        ("date-difference.html", "📅", "Date Difference", "Calculate date differences"),
        ("discount.html", "🏷️", "Discount Calculator", "Calculate discounts"),
        ("emi.html", "🏦", "EMI Calculator", "Calculate EMI"),
        ("gst.html", "💸", "GST Calculator", "Calculate GST"),
        ("loan.html", "💳", "Loan Calculator", "Calculate loan payments"),
        ("percentage.html", "📊", "Percentage Calculator", "Calculate percentages"),
        ("scientific.html", "🔬", "Scientific Calculator", "Scientific calculations"),
        ("simple.html", "🔢", "Simple Calculator", "Basic calculations"),
        ("sip.html", "📈", "SIP Calculator", "Calculate SIP returns"),
        ("speed-distance-time.html", "🏃", "Speed Distance Time", "Calculate speed/distance/time"),
        ("time.html", "⏰", "Time Calculator", "Time calculations"),
        ("tip.html", "💵", "Tip Calculator", "Calculate tips"),
        ("unit-cost.html", "💰", "Unit Cost Calculator", "Calculate unit costs"),
    ],
    "converters": [
        ("base64.html", "🔤", "Base64", "Encode/decode Base64"),
        ("binary-decimal.html", "🔢", "Binary/Decimal", "Convert binary and decimal"),
        ("case.html", "🔡", "Case Converter", "Convert text case"),
        ("color.html", "🎨", "Color Converter", "Convert color formats"),
        ("csv-to-json.html", "📊", "CSV to JSON", "Convert CSV to JSON"),
        ("file-size.html", "📏", "File Size Converter", "Convert file sizes"),
        ("hex-ascii.html", "🔤", "Hex/ASCII", "Convert hex and ASCII"),
        ("hex-rgb.html", "🎨", "Hex/RGB", "Convert hex and RGB"),
        ("html-to-text.html", "📄", "HTML to Text", "Convert HTML to text"),
        ("jpg-png.html", "🖼️", "JPG/PNG Converter", "Convert JPG and PNG"),
        ("json-formatter.html", "📦", "JSON Formatter", "Format JSON"),
        ("json-to-csv.html", "📊", "JSON to CSV", "Convert JSON to CSV"),
        ("markdown-html.html", "📝", "Markdown/HTML", "Convert Markdown and HTML"),
        ("roman-numeral.html", "🏛️", "Roman Numerals", "Convert Roman numerals"),
        ("temperature.html", "🌡️", "Temperature", "Convert temperatures"),
        ("text-binary.html", "🔢", "Text/Binary", "Convert text and binary"),
        ("text-to-html.html", "📄", "Text to HTML", "Convert text to HTML"),
        ("unit-converter.html", "📏", "Unit Converter", "Convert units"),
        ("url.html", "🔗", "URL Encode/Decode", "Encode/decode URLs"),
        ("webp-converter.html", "⚡", "WebP Converter", "Convert to/from WebP"),
        ("xml-json.html", "📋", "XML/JSON", "Convert XML and JSON"),
        ("yaml-json.html", "📋", "YAML/JSON", "Convert YAML and JSON"),
    ],
    "text": [
        ("char-counter.html", "🔢", "Character Counter", "Count characters and words"),
        ("duplicate-finder.html", "🔍", "Duplicate Finder", "Find duplicate lines"),
        ("find-replace.html", "🔎", "Find & Replace", "Find and replace text"),
        ("html-formatter.html", "💻", "HTML Formatter", "Format HTML code"),
        ("html-minifier.html", "📦", "HTML Minifier", "Minify HTML"),
        ("json-formatter.html", "📋", "JSON Formatter", "Format JSON"),
        ("json-viewer.html", "👁️", "JSON Viewer", "View JSON with syntax highlighting"),
        ("keyword-density.html", "📊", "Keyword Density", "Analyze keyword density"),
        ("line-break-remover.html", "📝", "Line Break Remover", "Remove line breaks"),
        ("markdown-preview.html", "📖", "Markdown Preview", "Preview Markdown"),
        ("paragraph-counter.html", "📄", "Paragraph Counter", "Count paragraphs"),
        ("readability-checker.html", "📖", "Readability Checker", "Check text readability"),
        ("regex-tester.html", "🔧", "Regex Tester", "Test regular expressions"),
        ("remove-duplicates.html", "🗑️", "Remove Duplicates", "Remove duplicate lines"),
        ("remove-spaces.html", "␣", "Remove Spaces", "Remove extra spaces"),
        ("sentence-counter.html", "📝", "Sentence Counter", "Count sentences"),
        ("slug-generator.html", "🔗", "Slug Generator", "Generate URL slugs"),
        ("text-compare.html", "🔄", "Text Compare", "Compare two texts"),
        ("text-reverser.html", "🔄", "Text Reverser", "Reverse text"),
        ("text-sorter.html", "🔤", "Text Sorter", "Sort lines of text"),
        ("toc-generator.html", "📑", "TOC Generator", "Generate table of contents"),
        ("word-counter.html", "📊", "Word Counter", "Count words"),
    ],
    "image": [
        ("base64-to-image.html", "🖼️", "Base64 to Image", "Convert Base64 to image"),
        ("blur-image.html", "💫", "Blur Image", "Blur images"),
        ("brightness-contrast.html", "🌟", "Brightness/Contrast", "Adjust brightness and contrast"),
        ("grayscale.html", "⚫", "Grayscale", "Convert to grayscale"),
        ("image-cropper.html", "✂️", "Image Cropper", "Crop images"),
        ("image-resizer.html", "📐", "Image Resizer", "Resize images"),
        ("image-rotator.html", "🔄", "Image Rotator", "Rotate images"),
        ("image-to-base64.html", "📋", "Image to Base64", "Convert image to Base64"),
        ("meme-generator.html", "😂", "Meme Generator", "Create memes"),
    ],
    "pdf": [
        ("add-image.html", "🖼️", "Add Image to PDF", "Add images to PDF"),
        ("add-page-numbers.html", "🔢", "Add Page Numbers", "Add page numbers to PDF"),
        ("add-text.html", "📝", "Add Text to PDF", "Add text to PDF"),
        ("pdf-to-image.html", "🖼️", "PDF to Image", "Convert PDF pages to images"),
        ("remove-pages.html", "🗑️", "Remove Pages", "Remove PDF pages"),
        ("reorder-pages.html", "🔀", "Reorder Pages", "Reorder PDF pages"),
        ("rotate-pdf.html", "🔄", "Rotate PDF", "Rotate PDF pages"),
        ("split-pdf.html", "✂️", "Split PDF", "Split PDF into pages"),
    ],
    "dev": [
        ("browser-info.html", "🌐", "Browser Info", "View browser information"),
        ("color-picker.html", "🎨", "Color Picker", "Pick colors"),
        ("cookie-viewer.html", "🍪", "Cookie Viewer", "View cookies"),
        ("ip-lookup.html", "🌐", "IP Lookup", "Lookup IP address"),
        ("jwt-decoder.html", "🔐", "JWT Decoder", "Decode JWT tokens"),
        ("screen-resolution.html", "🖥️", "Screen Resolution", "View screen resolution"),
        ("storage-viewer.html", "💾", "Storage Viewer", "View localStorage"),
        ("timestamp.html", "⏰", "Timestamp", "Unix timestamp tools"),
        ("unix-time.html", "⏰", "Unix Time", "Unix time converter"),
    ],
}

# Count totals
totals = {cat: len(tools) for cat, tools in tools_data.items()}
total_tools = sum(totals.values())

print(f"Total tools: {total_tools}")
print("Category counts:")
for cat, count in totals.items():
    print(f"  {cat}: {count}")
